airflow_version: 2.5.2
airflow_user: airflow
airflow_group: airflow
airflow_fuse_group: airflow-fuse
airflow_db_name: airflow
airflow_home: /opt/airflow
#airflow_admin_username: demo                     # change it 
#airflow_admin_password: demo                     # chamge it
airflow_port: 5080
airflow_dag_dir: /var/data/airflow
airflow_s3_bucket: airflow
