cluster_name: opensearch
opensearch_dir: /opt/opensearch
opensearch_port: 9200
opensearch_dashboard_dir: /opt/opensearch-dashboard
opensearch_dashboard_port: 5601
opensearch_user: opensearch
opensearch_group: opensearch
opensearch_home: /home/opensearch
opensearch_config: /etc/opensearch  
opensearch_dashboard_config: /etc/opensearch-dashboard  

opensearch_data: /var/lib/opensearch  
opensearch_log:  /var/log/opensearch

opensearch_xms_value: 1
opensearch_xmx_value: 1
  

opensearch_subject: CN=example.com,OU=Unit,O=Organization,L=City,ST=State,C=US  
