#passphrase: "/usr/sbin/blkid | /usr/bin/grep UUID | /usr/bin/grep sda | /usr/bin/head -n 1 | /usr/bin/awk -F' ' '{print $2}' |  /usr/bin/awk -F'=' '{print $2}' | /usr/bin/sed 's/.$//' | /usr/bin/sed 's/^.//'"
#passphrase: "cat /sys/class/dmi/id/product_uuid"
passphrase: "cat /etc/machine-id"
