trino_user: trino
trino_group: trino
trino_home: /opt/trino
trino_jvm_mx: Xmx1G                           ##  adjust it
trino_data_dir: /var/trino/data
trino_port: 7080
trino_tls_port: 7443
trino_password_dir: /etc/trino/
trino_password_file: /etc/trino/passwdfile
