trino_user: trino
trino_group: trino
#trino_url: https://repo1.maven.org/maven2/io/trino/trino-server/410/trino-server-410.tar.gz
#trino_file_name: trino-server-410
trino_home: /opt/trino
trino_jvm_mx: Xmx1G                           ##  adjust it
trino_data_dir: /var/trino/data
trino_port: 7080
trino_tls_port: 7443
#trino_cli_url: https://repo1.maven.org/maven2/io/trino/trino-cli/410/trino-cli-410-executable.jar
#trino_cli_file: trino-cli-410-executable.jar
shared_secret: bhujd3456ndswu5!&df
trino_password_dir: /etc/trino/
trino_password_file: /etc/trino/passwdfile
