---

- name: create {{ opensearch_dir }}
  file:
     path: '{{ opensearch_dir }}'
     state: directory
     owner: '{{ opensearch_user }}'
     group: '{{ opensearch_group }}'

- name: download the opensearch binary
  get_url:
     url: "http://{{ hostvars[groups['repo'][0]]['ansible_host'] }}/download/ opensearch-{{ lookup('env', 'OPENSEARCH') }}-linux-x64.deb"
     dest: /opt
  register: opensearch_download
  # notify: restart opensearch


- name: Reload service files
  systemd:
    daemon_reload: true       
