---

- name: copy  keycloak.conf file
  template: src='{{ item.src }}' dest='{{ item.dest }}'
  loop:
     - { src: 'keycloak.conf.j2', dest: '{{ keycloak_home }}/conf/keycloak.conf'  }
     - { src: 'keycloak.service.j2', dest: '/etc/systemd/system/keycloak.service'  }
  notify: restart start_keycloak   

- name: Reload service files
  systemd:
    daemon_reload: true

- name: flush the handeler
  meta: flush_handlers
