---
- name: sleep for 15 sec
  shell: sleep 15

- name: connect to kecloak
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode='0550'
  loop:
     - { src: 'realm.sh.j2', dest: '{{ tmpfs_dir }}/kcadm/realm.sh'  }
  become: yes
  become_user: '{{ kcadm_user }}' 

- name: run the srcipt
  shell: '{{ tmpfs_dir }}/{{ kcadm_user }}/realm.sh; rm -f {{ tmpfs_dir }}/{{ kcadm_user }}/realm.sh'
  become: yes
  become_user: '{{ kcadm_user }}' 
  ignore_errors: yes
