- name: Check that the python link exists
  stat:
      path: '/usr/bin/python'
  register: python_stat_result

- name: create soft link to /usr/bin/python
  file:
    src: '/usr/bin/python3'
    dest: '/usr/bin/python'
    state: link

- name: Install python3-pip, jre and postgresql-client
  apt:
    name: '{{ item }}'
    update_cache: yes
  loop:
    - python3-pip
    - python3-dev
    #- postgresql-client-{{ postgresql_version }}     
    - postgresql-client    
    - '{{ java_jdk }}'
    - s3fs
    - apache2-utils  
    - net-tools 
    - ntp

- name: Check that the hadoop home exists
  stat:
      path: '{{ hadoop_home }}'
  register: hadoop_stat_result

- name : extract hadoop  zip
  unarchive:
     src: "http://{{ groups['repo'][0] }}/download/{{ hadoop_file_name }}.tar.gz"
     dest: /opt
     remote_src: true
     owner: '{{ hadoop_user }}'
     group: '{{ hadoop_group }}'
  when: not hadoop_stat_result.stat.exists

- name: create soft link to /opt/hadoop
  file:
    src: '/opt/{{ hadoop_file_name }}'
    dest: '{{ hadoop_home }}'
    state: link
  
     
