- name: Copy journal template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "journald.conf.j2", dest: "/etc/systemd/journald.conf" }
  notify:
    - restart journald    
