---

- name: Create ranger directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ ranger_user }}'
    group: '{{ ranger_group }}'
    mode: '0755'
  loop:
    - '{{ ranger_dir }}'
    - '{{ ranger_config_dir }}'

- name: get extra jar files
  get_url:
     url: '{{ item }}'
     dest: '{{ ranger_dir }}'
     owner: '{{ ranger_user }}'
     group: '{{ ranger_group }}'
  loop:
     - "http://{{ hostvars[groups['repo'][0]]['ansible_host'] }}/download/{{ postgresql_connector_file_name }}" 

- name: copy  opensearch.service opensearch.yml
  template: src='{{ item.src }}' dest='{{ item.dest }}' owner={{ ranger_user }} group={{ ranger_group }}  mode=0755
  loop:
     - { src: 'ranger.service.j2', dest: '/etc/systemd/system/ranger.service'  }  
  #notify: restart ranger     

- name: Reload service files
  systemd:
    daemon_reload: true       
