- name: install nginx
  apt:
     name: nginx      
  notify: restart nginx

- name: copy  static-file-server.conf
  template: src='static-file-server.conf.j2' dest='/etc/nginx/conf.d/static-file-server.conf'
  notify: restart nginx

- name: Flush handlers
  meta: flush_handlers  

- name: create a java dir
  file:
     path: /var/data/download     
     state: directory
     
- name : download  hadoop  zip
  get_url:
     url: '{{ hadoop_url }}'
     dest: /var/data/download

- name : download  hadoop aws  zip
  get_url:
     url: '{{ hadoop_aws_url }}'    
     dest: /var/data/download

- name : download  aws_java_sdk_bundle_url  zip
  get_url:
     url: '{{ aws_java_sdk_bundle_url }}' 
     dest: /var/data/download

- name : download  awssdk_bundle zip
  get_url:
     url: '{{ awssdk_bundle_url }}' 
     dest: /var/data/download

- name : download  url_connection_client  zip
  get_url:
     url:  '{{ url_connection_client_url }}'
     dest: /var/data/download

- name : download  iceberg_spark_runtime  zip
  get_url:
     url:  '{{ iceberg_spark_runtime_url }}'   
     dest: /var/data/download

- name : download  hive_metastore : zip
  get_url:
     url:  '{{ hive_metastore_url }}' 
     dest: /var/data/download

- name : download  postgresql_connector  zip
  get_url:
     url:   '{{ postgresql_connector_url }}' 
     dest: /var/data/download

- name : download  monio zip
  get_url:
     url:  '{{ minio_url }}'
     dest: /var/data/download

- name : download  minio cli  zip
  get_url:
     url:  '{{ minio_cli_url }}'
     dest: /var/data/download

- name : download  trino zip
  get_url:
     url: '{{ trino_url }}' 
     dest: /var/data/download

- name : download  keycloak zip
  get_url:
     url: '{{ keycloak_url }}' 
     dest: /var/data/download

- name : download zookeeper zip
  get_url:
     url: '{{ zookeeper_url }}' 
     dest: /var/data/download

- name : download  trino cli zip
  get_url:
     url: '{{ trino_cli_url }}' 
     dest: /var/data/download

- name : download  prome  zip
  get_url:
     url:  '{{ prometheus_url }}'
     dest: /var/data/download

- name : download  node_exporter_url zip
  get_url:
     url: '{{ node_exporter_url }}'  
     dest: /var/data/download

- name : download  grafana  zip
  get_url:
     url:  '{{ grafana_url }}'  
     dest: /var/data/download



- name: Check that the  /usr/local/sbin/mc exists
  stat:
      path: '/usr/local/sbin/mc'
  register: stat_result

- name: set up the minio cli       
  shell: 'cp /var/data/download/mc /usr/local/sbin/mc; chmod 755 /usr/local/sbin/mc; '
  when: not stat_result.stat.exists

- name: Check that the /usr/local/sbin/trino exists
  stat:
      path: '/usr/local/sbin/trino'
  register: stat_result

- name: set up the minio cli
  shell: 'cp {{ trino_cli_file }} /usr/local/sbin/trino; chmod 755 /usr/local/sbin/trino; '
  when: not stat_result.stat.exists       
