---

- name: Create /etc/jupyterhub
  file:
    path: /etc/jupyterhub
    state: directory
    mode: '0775'
    group: jupyterhub

- name: Create {{ jupyterhub_home }}
  file: 
     path:  '{{ jupyterhub_home }}'
     state: directory

      
- name: install jupyterhub and notebook
  become: yes
  become_user: '{{ jupyterhub_user }}'
  pip: 
    name: '{{ item }}'
  loop:
    - jupyterhub=={{ lookup('env', 'JUPYTERHUB') }}
    - Jupyterlab=={{ lookup('env', 'JUPYTERLAB') }}
    - notebook=={{ lookup('env', 'NOTEBOOK') }}
    - oauthenticator=={{ lookup('env', 'OAUTHENTICATOR') }}
    - psycopg2-binary=={{ lookup('env', 'PSYCOPG2_BINARY') }} 
    - jupyterlab-theme-solarized-dark  
    - plotly=={{ lookup('env', 'PLOTLY') }}
    - seaborn=={{ lookup('env', 'SEABORN') }}
    - matplotlib=={{ lookup('env', 'MATPLOTLIB') }}
    - numpy=={{ lookup('env', 'NUMPY') }}
    - pandas=={{ lookup('env', 'PANDAS') }}
    - scikit-learn=={{ lookup('env', 'SCIKIT_LEARN') }}
    - scikit-image=={{ lookup('env', 'SCIKIT_IMAGE') }}
    - statsmodels=={{ lookup('env', 'STATSMODELS') }}
    - s3cmd=={{ lookup('env', 'S3CMD') }}
    - ipython-sql=={{ lookup('env', 'IPYTHON_SQL') }}
    - sparksql-magic=={{ lookup('env', 'SPARKSQL_MAGIC') }}
    - sqlalchemy-trino=={{ lookup('env', 'SQLALCHEMY_TRINO') }}
    #- clickhouse-driver
    #- clickhouse-sqlalchemy
    #- tensorflow=={{ lookup('env', 'HADOOP_VERSION') }}
    #- torch=={{ torch }}  
    #- pyarrow==11.0.0 
  
   

- name: install configurable-http-proxy
  npm:
    name: configurable-http-proxy      
    global: yes

