- name: install postgresql
  apt:
     name: ['haproxy']
     update_cache: yes

- name: copy haproxy config file
  template: src='{{ item.src }}' dest='{{ item.dest }}'
  loop:
     - { src: 'haproxy.cfg.j2', dest: '/etc/haproxy/haproxy.cfg'  }
     - { src: 'haproxy.service.j2', dest: '/lib/systemd/system/haproxy.service'  }
  notify: restart haproxy

- name: Reload service files
  systemd:
    daemon_reload: true
