---

- name: copy keycloak.conf file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  loop:
    - { src: 'keycloak.conf.j2', dest: '{{ keycloak_home }}/conf/keycloak.conf', mode: '0644' }
    - { src: 'run-keycloak.sh.j2', dest: '{{ keycloak_home }}/run-keycloak.sh', mode: '0755' }
    - { src: 'keycloak.service.j2', dest: '/etc/systemd/system/keycloak.service', mode: '0644' }
  notify: restart start_keycloak

- name: Reload service files
  systemd:
    daemon_reload: true

- name: flush the handeler
  meta: flush_handlers
