---
- name: clean hadoop
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        rm -fr /etc/cert.d
