---
- name: clean java
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
         rm -rf /usr/lib/jvm/jdk-24.0.1-oracle-x64
         apt remove --purge -y openjdk-17-jdk  python3-dev postgresql-client s3fs \
              apache2-utils ntp python3-pip python3-venv libldap2-dev libffi-dev libssl-dev \
              libsasl2-dev libpq-dev libcurl4-openssl-dev libssl-dev build-essential 
