---
- name: clean spark
  hosts: hive_metastore*
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        systemctl  stop    hive-metastore
        systemctl  disable   hive-metastore
        rm -fr /opt/apache-hive*
        rm -fr /etc/systemd/system/hive*
        systemctl daemon-reload
        systemctl reset-failed
        sudo -u postgres psql -c "DROP DATABASE IF EXISTS hive;"
        sudo -u postgres psql -c "CREATE DATABASE hive;"
