---
- name: Stop keycloak remove service, unmount and wipe disks (all in one shell)
  hosts:  keycloak*
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        systemctl stop keycloak
        systemctl disable keycloak
        rm -f /etc/systemd/system/keycloak.service
        rm -rf /opt/keycloak*
        systemctl daemon-reload
        systemctl reset-failed


