---
- name: Stop keycloak remove service, unmount and wipe disks (all in one shell)
  hosts:  keycloak*
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        systemctl stop keycloak
        systemctl disable keycloak
        rm -f /etc/systemd/system/keycloak.service
        rm -rf /opt/keycloak*
        systemctl daemon-reload
        systemctl reset-failed
        sudo -u  postgres psql -d keycloak -tAc "DROP PUBLICATION IF EXISTS pub_keycloak_1;"
        sudo -u  postgres psql -d keycloak -tAc "DROP PUBLICATION IF EXISTS pub_keycloak_2;"
        sudo -u postgres psql -d keycloak -tAc "SELECT subname FROM pg_subscription;" | while read -r sub; do
          if [ -n "$sub" ]; then
            sudo -u postgres psql -d keycloak -c "ALTER SUBSCRIPTION \"$sub\" DISABLE;"
            sudo -u postgres psql -d keycloak -c "ALTER SUBSCRIPTION \"$sub\" SET (slot_name = NONE);"
            sudo -u postgres psql -d keycloak -c "DROP SUBSCRIPTION \"$sub\";"
          fi
        done
        sudo -u postgres psql -c "DROP DATABASE IF EXISTS keycloak;"
        sudo -u postgres psql -c "CREATE DATABASE keycloak;"


