---
- name: clean postgresql
  hosts: postgresql
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        apt remove --purge -y postgresql-14
        apt remove --purge -y postgresql-client-14
        systemctl daemon-reload
        systemctl reset-failed
