---
- name: clean postgresql
  hosts: postgresql
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        sudo systemctl stop postgresql
        sudo systemctl stop postgresql@16-main
        sudo apt-get --purge remove postgresql-16 postgresql-client-16 postgresql-contrib-16 -y
        sudo apt-get --purge remove postgresql postgresql-* libpq-dev postgresql-common -y
        sudo apt-get --purge remove postgresql postgresql-* libpq-dev postgresql-common -y
        sudo rm -rf /var/lib/postgresql/16
        sudo rm -rf /etc/postgresql/16
        sudo rm -rf /etc/postgresql-common
        sudo rm -rf /var/log/postgresql
        sudo rm -rf /var/run/postgresql
        sudo apt-get autoremove --purge -y
        sudo apt-get autoclean
