---
- name: clean  secret
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
         rm -f /usr/lib/java/secret.jceks
         rm -f /usr/lib/java/.secret.jceks.crc
         rm -fr /etc/lockbox/
      
