---
- name: clean spark
  hosts: spark*
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        umount -f /var/data/spark-app
        systemctl stop spark-master
        systemctl disable spark-master
        systemctl stop  spark-worker-1
        systemctl stop  spark-worker-2
        systemctl stop  spark-worker-3
        systemctl stop  spark-worker-4
        systemctl stop  spark-history
        systemctl disable spark-worker-1
        systemctl disable spark-worker-2
        systemctl disable spark-worker-3
        systemctl disable spark-worker-4
        systemctl disable spark-history
        rm -fr /opt/spark*
        rm -fr /etc/systemd/system/spark*
        systemctl daemon-reload
        systemctl reset-failed
