---
- name: Stop supserset, remove service, unmount and wipe disks (all in one shell)
  hosts:  superset*
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        systemctl stop superset
        systemctl disable superset
        systemctl stop superset_keycloak
        systemctl disable superset_keycloak
        rm -f /etc/systemd/system/superset*.service
        rm -rf /opt/superset/
        systemctl daemon-reload
        systemctl reset-failed
        sudo -u postgres psql -c "DROP DATABASE IF EXISTS superset;"
        sudo -u postgres psql -c "CREATE DATABASE superset;"


