---
- name: clean zookeper
  hosts: zookeeper
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3   

  tasks:
    - name: Full cleanup in one shell block
      shell: |
        systemctl stop  zookeeper
        rm -fr /opt/*zookeeper*
        systemctl daemon-reload
