- name: Copy Superset template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ superset_user }}"
    mode: "{{ item.mode | default(omit) }}"  
  loop:
    - { src: "superset_config.py.j2", dest: "{{ superset_home }}/non-keycloak/superset_config.py" }
    - { src: "run_superset.sh.j2", dest: "{{ superset_home }}/non-keycloak/run_superset.sh",  mode: "0755" } 
    - { src: "run_superset_keycloak.sh.j2", dest: "{{ superset_home }}/keycloak/run_superset_keycloak.sh",  mode: "0755" } 
    - { src: "client_secret.json.j2", dest: "{{ superset_home }}/keycloak/client_secret.json"} 
    - { src: "keycloak_security_manager.py.j2", dest: "{{ superset_home }}/pythonpath/keycloak_security_manager.py"} 
    - { src: "superset_config_keycloak.py.j2", dest: "{{ superset_home }}//keycloak/superset_config.py" } 
    - { src: "superset.service.j2", dest: "/etc/systemd/system/superset.service" } 
    - { src: "superset_keycloak.service.j2", dest: "/etc/systemd/system/superset_keycloak.service" } 
  notify: 
    - restart superset     
    - restart superset_keycloak     


- name: Initialize Superset database
  shell: |
        source {{ superset_venv_path }}/bin/activate
        export SUPERSET_CONFIG_PATH={{ superset_home }}/non-keycloak/superset_config.py
        export FLASK_APP=superset
        export PYTHONPATH={{ superset_home }}/pythonpath
        eval "$({{ secret_dir }}/{{ decrypt_file }})"
        {{ superset_venv_path }}/bin/superset db upgrade
        {{ superset_venv_path }}/bin/superset fab create-admin --username $SUPERSET_ADMIN_USER --firstname Superset --lastname Admin --email admin@superset.com --password $SUPERSET_ADMIN_PASSWORD
        {{ superset_venv_path }}/bin/superset init
  ignore_errors: true

# Reload systemd to recognize the new service definition
- name: Reload systemd daemon
  systemd:
    daemon_reload: true       
