- name: Install python3-pip, jre and postgresql-client
  apt:
    name: '{{ item }}'
    update_cache: yes
  loop:
    - python3-dev
    - postgresql-client    
    - '{{ java_jdk_17 }}'
    - s3fs
    - apache2-utils  
    - ntp
    - python3-pip
    - python3-venv  
    - libldap2-dev
    - libffi-dev 
    - libssl-dev 
    - libsasl2-dev
    - libpq-dev
    - libcurl4-openssl-dev
    - libssl-dev
    - build-essential

- name: Check if Java 24 is installed
  ansible.builtin.shell: |
    java -version 2>&1 | grep '\"24'
  register: java_check
  ignore_errors: yes      

- name: download the java 24 binary
  get_url:
     url: "http://{{ hostvars[groups['repo'][0]]['ansible_host'] }}/download/{{ jave_file_name }}"
     dest: /opt
  when:
    - java_check.rc != 0
    - java_file.stat.exists

- name: Install the java  package
  become: yes
  command: "dpkg -i /opt/{{ jave_file_name }}"
  when:
    - java_check.rc != 0
    - java_file.stat.exists

- name: Delete a  /opt/{{ jave_file_name }} on the remote host
  ansible.builtin.file:
    path: /opt/{{ jave_file_name }}
    state: absent    
