- name: Install python3-pip, jre and postgresql-client
  apt:
    name: '{{ item }}'
    update_cache: yes
  loop:
    #- python3-dev
    - postgresql-client    
    #- '{{ java_jdk }}'
    - s3fs
    - apache2-utils  
    - ntp



- name: download the java binary
  get_url:
     url: "http://{{ hostvars[groups['repo'][0]]['ansible_host'] }}/download/{{ jave_file_name }}"
     dest: /opt

- name: Install the java  package
  become: yes
  command: "dpkg -i /opt/{{ jave_file_name }}"

- name: Delete a  /opt/{{ jave_file_name }} on the remote host
  ansible.builtin.file:
    path: /opt/{{ jave_file_name }}
    state: absent    
