
- name:  create PUBLICATION
  shell: >
    PGPASSWORD={{ db_password }} psql -U {{ db_user }} -h {{ hostvars['node1']['ansible_host'] }} -d hive -c 'CREATE PUBLICATION pub_hive_1 FOR TABLE "ROLES","CTLGS","SERDES","GLOBAL_PRIVS","COLUMNS_V2","VERSION","TBLS","CDS","TABLE_PARAMS","SDS","DBS","SEQUENCE_TABLE","NOTIFICATION_SEQUENCE";';
    PGPASSWORD={{ db_password }} psql -U {{ db_user }} -h {{ hostvars['node2']['ansible_host'] }} -d hive -c 'CREATE PUBLICATION pub_hive_2 FOR TABLE "ROLES","CTLGS","SERDES","GLOBAL_PRIVS","COLUMNS_V2","VERSION","TBLS","CDS","TABLE_PARAMS","SDS","DBS","SEQUENCE_TABLE","NOTIFICATION_SEQUENCE";';
  delegate_to: localhost
  ignore_errors: yes  


- name: Create SUBSCRIPTION sub_hive_1 and sub_hive_2
  shell: |
    PGPASSWORD={{ db_password }} psql -U {{ db_user }} -h {{ hostvars['node1']['ansible_host'] }} -d hive -c \
    "CREATE SUBSCRIPTION sub_hive_1 \
    CONNECTION 'host={{ hostvars['node2']['ansible_host'] }} user={{ db_user }} password={{ db_password }} dbname=hive' \
    PUBLICATION pub_hive_2 WITH (copy_data = false, origin = 'none');"

    PGPASSWORD={{ db_password }} psql -U {{ db_user }} -h {{ hostvars['node2']['ansible_host'] }} -d hive -c \
    "CREATE SUBSCRIPTION sub_hive_2 \
    CONNECTION 'host={{ hostvars['node1']['ansible_host'] }} user={{ db_user }} password={{ db_password }} dbname=hive' \
    PUBLICATION pub_hive_1 WITH (copy_data = false, origin = 'none');"
  delegate_to: localhost
  ignore_errors: yes
    
