---

- name: Create /etc/jupyterhub
  file: 
     path:  /etc/jupyterhub
     state: directory

- name: Create {{ jupyterhub_home }}
  file: 
     path:  '{{ jupyterhub_home }}'
     state: directory

- name: Install nodejs and npm (and python3-pip)
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - nodejs
    - python3-pip
  when: ansible_facts.packages is not defined or ansible_facts.packages["nodejs"] is not defined

      
- name: install jupyterhub and notebook
  pip: 
    name: '{{ item }}'
  loop:
    - jupyterhub=={{ jupyterhub }}      
    - JupyterLab=={{ jupyterlab }}
    - notebook=={{ notebook }}  
    - oauthenticator=={{ oauthenticator }}
    - plotly=={{ plotly }} 
    - seaborn=={{ seaborn }}
    - matplotlib=={{ matplotlib }} 
    - numpy=={{ numpy }}
    - pandas=={{ pandas }}
    #- torch=={{ torch }}  
    #- pyarrow==11.0.0 
    - scikit-learn=={{ scikit_learn }} 
    - scikit-image=={{ scikit_image }}
    - statsmodels=={{ statsmodels }}  
    - s3cmd==2.4.0
    - ipython-sql==0.5.0
    - sqlalchemy== {{ sqlalchemy }}
    - sparksql-magic==0.0.3  
    - sqlalchemy-trino==0.5.0
    #- clickhouse-driver
    #- clickhouse-sqlalchemy
    - tensorflow==2.12.0  

- name: install configurable-http-proxy
  npm:
    name: configurable-http-proxy      
    global: yes


