---
- name: Install Keepalived
  apt:
     name: keepalived
     state: present
     update_cache: yes

- name: Configure Keepalived
  template:
     src: keepalived.conf.j2
     dest: /etc/keepalived/keepalived.conf

- name: Enable and start Keepalived
  systemd:
     name: keepalived
     enabled: yes
     state: restarted
