- name: Add postgres user to ssl-cert group (required for SSL access)
  user:
    name: postgres
    groups: ssl-cert
    append: yes

- name: Add PostgreSQL APT key
  get_url:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      dest: /tmp/pg.asc

- name: Import PostgreSQL key
  shell: |
      gpg --dearmor < /tmp/pg.asc > /etc/apt/trusted.gpg.d/postgresql.gpg
  args:
      creates: /etc/apt/trusted.gpg.d/postgresql.gpg

- name: Add PostgreSQL APT repository
  apt_repository:
     repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
     filename: 'pgdg'
     state: present

- name: Update apt cache
  apt:
     update_cache: yes

- name: Install postgresql
  apt:
     name:
        - postgresql-{{ pg_version }}
        - postgresql-client-16
- name: Ensure PostgreSQL 16 service is enabled and started
  systemd:
    name: postgresql@16-main
    state: started
    enabled: yes          
- name: Wait for PostgreSQL to be ready
  wait_for:
    port: 5432
    host: 127.0.0.1
    delay: 2
    timeout: 30

- name: Create db user
  postgresql_user:
    name: "{{ lookup('env', 'PGUSER') }}"
    password: "{{ lookup('env', 'PGPASSWORD') }}x "
    state: present
  become: yes
  become_user: postgres

- name: Allow remote access - postgresql.conf
  template:
      src: postgresql.conf.j2
      dest: "{{ pg_conf_path }}/postgresql.conf"
      owner: postgres
      group: postgres
      mode: '0644'
  notify: Restart PostgreSQL

- name: Allow remote access - pg_hba.conf
  template:
     src: pg_hba.conf.j2
     dest: "{{ pg_conf_path }}/pg_hba.conf"
     owner: postgres
     group: postgres
     mode: '0640'
  notify: Restart PostgreSQL    


- name: Enable publication for all tables in each database
  become_user: postgres
  postgresql_query:
    db: "{{ item }}"
    query: "CREATE PUBLICATION mypub FOR ALL TABLES;"
  loop:
    - myapp_db
    - myother_db
    - another_db
  when: inventory_hostname == 'node1'


- name: Subscribe to replication from node1 for each database
  become_user: postgres
  postgresql_query:
    db: "{{ item }}"
    query: >
      CREATE SUBSCRIPTION mysub
      CONNECTION 'host={{ hostvars["node1"]["ansible_host"] }} port=5432 dbname={{ item }} user=replicator password=replicator_password'
      PUBLICATION mypub
      WITH (copy_data = true);
  loop:
    - myapp_db
    - myother_db
    - another_db
  when: inventory_hostname == 'node2'

