---

- name: Create mount point dir
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ minio_group }}"
  loop:
    - { path: '/mnt/disk1', owner: '{{ minio_user }}'}
    - { path: '/mnt/disk2', owner: '{{ minio_user }}'}

- name: Create a xfs filesystem on /dev/sd*
  command: mkfs.xfs "{{ item.path }}"  -L "{{ item.label }}"
  loop:
    - { path: '/dev/sdb', label: 'DISK1'}
    - { path: '/dev/sdc', label: 'DISK2'}
  ignore_errors: true         

- name: Mount up device by label
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: xfs
    state: present    
  loop:
    - { path: '/mnt/disk1', src: 'LABEL=DISK1'}
    - { path: '/mnt/disk2', src: 'LABEL=DISK2'}
  ignore_errors: true         

- name: mount all the disks
  command: mount -a

- name: Create minio dir for each mount point
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ minio_group }}"
  loop:
    - { path: '/mnt/disk1/minio', owner: '{{ minio_user }}'}
    - { path: '/mnt/disk2/minio', owner: '{{ minio_user }}'}


