---


- name: create {{ minio_dir }}
  file:    
     path: '{{ minio_dir }}'
     state: directory
     owner: '{{ minio_user }}'
     group: '{{ minio_group }}'


- name: download the minio binary
  get_url:
     url: "http://{{ hostvars[groups['repo'][0]]['ansible_host'] }}/download/{{ minio_url_file }}" 
     dest: /opt 
  register: minio_download
  notify: restart minio     

- name: Install the MinIO package
  become: yes
  command: "dpkg -i /opt/{{ minio_url_file }}"
  when: minio_download.changed    

- name: Delete a  /opt/{{ minio_url_file }} on the remote host
  ansible.builtin.file:
    path: /opt/{{ minio_url_file }}
    state: absent    

- name: copy  minio env files
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode='{{ item.mode }}' owner='{{ minio_user }}' group='{{ application_group }}'
  loop:
     - { src: 'minio.j2', dest: '/etc/default/minio', mode: 0644 }
     - { src: 'run-minio.sh.j2', dest: '/opt/minio/run-minio.sh', mode: 755 }
     - { src: 'minio.service.j2', dest: '/etc/systemd/system/minio.service', mode: 644}
  notify: restart minio     
    
- name: Reload service files
  systemd:
    daemon_reload: true  
