- name: copy  service and config file
  template: src='{{ item.src }}' dest='{{ item.dest }}' mode=0750 group='{{ application_group }}'
  loop:
     - { src: 'jupyterhub.service.j2', dest: '/etc/systemd/system/jupyterhub.service'  }      
     - { src: 'jupyterhub_config_simple.py.j2', dest: '/opt/jupyterhub/jupyterhub_config_simple.py'  }      
     - { src: 'run_jupyterhub.sh.j2', dest: '/opt/jupyterhub/run_jupyterhub.sh'  }      
  notify: restart jupyterhub 

- name: Reload service files
  systemd:
    daemon_reload: true  

